POST http://localhost:3000/api/cards
Content-Type: application/json

{
  "agency": 5555,
  "account": 1345,
  "cpf": "01934859230",
  "dateOfBirth":29052004,
  "fullName": "icaro de oliveira macedo",
  "nameForCard": "icaro o macedo",
  "flag": "Visa",
  "type": "Gold",
  "expirationDate": "15",
  "password": 592861,
  "confirmPassword": 592861
}


###
GET http://localhost:3000/api/cards

###
GET http://localhost:3000/api/cards/search
Content-Type: application/json

{
  "number": 3034813004584186
}

###
PUT http://localhost:3000/api/cards/state
Content-Type: application/json

{
  "number": 3034813004584186,
  "agency": 5555,
  "account": 1345,
  "password": 592861,
  "confirmPassword": 592861,
  "state": "canceled",
  "motive": ""
}